### ISSUE TITLE
Plugin Maintanance

### ISSUE THREAD

**Issue by erapisardi** [halink0803/learnpress-ultimate-member-integration#1]
Hi,
I would like to know if this plugin is still maintained.

Thanks

**Comment by halink0803** [comment]
Hi @erapisardi,
Sorry to tell you that currently I don't have enough time to keep track on this. If you like it, please request on https://wordpress.org/plugins/learnpress/ for the development team to create an official plugin.
Best regards,

**Comment by erapisardi** [comment]
Hi
thank you for the reply. I already gave the link to your plugin to the Learnpress Staff. Hope they will develop an official version.

Regards,
